### ISSUE TITLE
Pipeline data helper function

### ISSUE THREAD

**Issue by ryanrichholt** [tgen/jetstream#101]
Recent changes encourage storing data and scripts in pipeline folders. One issue with this approach is maintaining the ability to identify changes to task commands. If a task calls a script from within the pipeline directory, users need to be very careful tracking changes to that script, or jetstream won't detect that the task behavior is modified. Example:

```
- name: taskA
  cmd: echo hello world 
```

vs

```
- name: taskA
   cmd: bash ${JS_PIPELINE_PATH}/script.sh
```

If any code changes in the first example, Jetstream will detect the task has changed, and rerun it the next time the pipeline is started on that project. But, in the second example, if script.sh changes, there is no way to tell. Best-practices would be to name the script with a version number, and increment if it ever changes. 

A helper function could be created to assist this process. During render, this would fetch an md5 checksum for the given file path. If the script changes, the comment will be altered, and the task identity will be changed forcing it to be reset:
```
- name: taskA
  cmd: |
    {{ watch_for_changes('script.sh') }}
    bash ${JS_PIPELINE_PATH}/script.sh
```

After rendering the task will look like this:
```
- name: taskA
  cmd: |
    # Pipeline file: script.sh md5sum: 02e70a7f9bb1e8077f393dcefbe4f832
    bash ${JS_PIPELINE_PATH}/script.sh
```

**Comment by PedalheadPHX** [comment]
I like the MD5 check idea, we are saving the files (copied from other repos) with the source commit ID in the filename.  But as you point out if we edit a script within a project then the changes in the script do not cause a restart. This is a good idea @awchrist @TGEN-BTurner
