### ISSUE TITLE
Container ids should be part of identity

### ISSUE THREAD

**Issue by ryanrichholt** [tgen/jetstream#117]
# Container ids 

This one is obviously part of the task identity. But, I want it to be as flexible as possible. 

# Reset directive

This one is more difficult. There is a problem currently with not being able to update task directives unless the task identity has changed. Maybe a better fix here would be to change the workflow mash function so that it always updates task directives, but only resets the task if the identity has changed.

Alternatively, we could just add the reset directive to the identity calculation. The big downside here is that if you have a workflow already run, adding reset directives to a task will reset it.

**Comment by PedalheadPHX** [comment]
@bryce-turner Isn't this issue resolved now?

**Comment by bryce-turner** [comment]
I didn't close this one with the release of v1.7.0 since the reset directive handling has not been updated. Could break this into a new issue and edit/close this issue with the focus on container ID.
