### ISSUE TITLE
Catching job status updates post failure

### ISSUE THREAD

**Issue by bryce-turner** [tgen/jetstream#121]
This has been a long standing issue that might be easier said than done. At the moment, if a slurm job fails due to a node failure within slurm, then the job gets requeued on the cluster with the same jobid. However, Jetstream will continue to see this as a failed job.

I think we can modify the implementation of the job monitor, we currently have:
```python3
    async def job_monitor(self):
        """Request job data updates from sacct for each job in self.jobs."""
        log.info('Slurm job monitor started!')
        failures = self.job_monitor_max_fails
        try:
            while 1:
                await self.wait_for_next_update()

                if not self.jobs:
                    log.debug('No current jobs to check')
                    self._bump_next_update()
                    continue
                try:
                    sacct_data = sacct(*self.jobs, return_data=True)
                except Exception:
                    if failures <= 0:
                        raise
                    else:
                        failures -= 1
                    err = f'Slurm job monitor error: {failures} remaining'
                    log.exception(err)
                    await asyncio.sleep(120)
                    continue

                failures = self.job_monitor_max_fails
                self._bump_next_update()

                for jid, data in sacct_data.items():
                    if jid in self.jobs:
                        job = self.jobs[jid]
                        job.job_data = data

                        if job.is_done() and job.event is not None:
                            job.event.set()
                            self.jobs.pop(jid)
```

We can pop the inactive/failed job into another dictionary that is then checked to see if the job status has been updated from the slurm side for which we could then consider the job as active.

Also, for tracking these changes in the log, we would need to update `    async def spawn(self, task):` to workout how to handle:
```python3
        if job.is_ok():
            log.info(f'Complete: {task.name}')
            task.complete(job.returncode())
        else:
            log.info(f'Failed: {task.name}')
            task.fail(job.returncode())
```
As we would not want to log every time a task is pending, but also to be aware when a job has been revived.

**Comment by ryanrichholt** [comment]
@bryce-turner Do you know what the status looks like when the job fails and gets requeued? Does it get a Failed status or this one:

NF NODE_FAIL
Job terminated due to failure of one or more allocated nodes.

I'm thinking that if automatic requeue is enabled in slurm, NF should be considered an "active" state.

**Comment by bryce-turner** [comment]
@ryanrichholt Unfortunately I did not catch the window of failure for the jobs that were requeued. Only noticed the job failing in the Jetstream log while the slurm log shows the job as completed with a single restart.

More broadly, I have seen jobs hit with a node failure and the job status is NODE_FAIL, but I don't think they always requeue (I've particularly noticed this failure to requeue with legacy pipelines). Which is part of the reason I suggested a secondary dictionary. 

Depending on implementation, I see a couple of potential pitfalls for this method. One could be that we are perpetually waiting for a job to requeue if we wait for the secondary dictionary to be empty. Or say we are in the final stages of pipeline and we have a job fail, but there are no more tasks for Jetstream to submit, so the run completes with a failed status and we no longer check the failed job.

**Comment by ryanrichholt** [comment]
@bryce-turner Thanks, Bryce. I think it's important to get to the bottom of how the requeue is controlled. 

Imagine a workflow with only one task. From the perspective of the Jetstream runner, if the job is in NF status, I only see two options:

1) Consider the job "active". The runner will keep checking Slurm for updates, and will not exit until this changes to a "done" (either failed or complete) state. 

2) Consider the job "failed". The runner will exit and indicate it has failed even though Slurm may immediately requeue this job.

If the workflow had more than one task, the time to choose path-1 or path-2 might change. I think we would still have to make the choice at some point.


Alternatively, the runner considers NF jobs active, and we implement some sort of internal timer on the job object. Each time the job data is updated, if the status is NF and has been for some period of time, it automatically changes to F.

**Comment by ryanrichholt** [comment]
@bryce-turner Are you guys still doing Wednesday meetings? If so, could you send me an invite so that I can chat with the HPC guys about the auto-requeue settings?
