### ISSUE TITLE
sbatch_args.extend causing 'NoneType' object has no attribute 'extend'

### ISSUE THREAD

**Issue by bryce-turner** [tgen/jetstream#125]
https://github.com/tgen/jetstream/blob/a20015ea80a9c75d9abbd5a976ec6bd980bed468/jetstream/backends/slurm.py#L182

When testing the development branch I ran into the following error. Commenting out the offending code line allows for successful slurm submissions. At first glance this appears to be because `sbatch_args` isn't defined? As it appears to be conditionally defined in an if statement on line 175.

```
exception=AttributeError("'NoneType' object has no attribute 'extend'",)>
Traceback (most recent call last):
  File "/home/bturner/.local/lib/python3.6/site-packages/jetstream/runner.py", line 271, in handler
    res = future.result()
  File "/home/bturner/.local/lib/python3.6/site-packages/jetstream/backends/slurm.py", line 182, in spawn
    sbatch_args.extend(task_sbatch_args)
AttributeError: 'NoneType' object has no attribute 'extend'
```

**Comment by PedalheadPHX** [comment]
Does this same issue exist in the current release version or is it unique to the development branch and maybe introduced by a pull request?

**Comment by ryanrichholt** [comment]
Looks like it was introduced back in March 2020 https://github.com/tgen/jetstream/commit/af94f9656d87593d2a0be8c3550624434b47b5de

I think the argument handling, even in the master branch, is wrong. It appends the arguments to the sbatch command if they are a string, extends otherwise. Seems to me like this would cause issues. Have you noticed any other issues?

I'll submit a PR to fix it.

**Comment by bryce-turner** [comment]
I haven't encountered any other issues that can be pinpointed to sbatch submissions. The only oddities I think I've seen that might be related to this is from the proteomics team using something similar to `sbatch_args: ['-t','7-00:00:00']` instead of `walltime:`. The only issue here was precedence of the arguments, wherein they expected a 7 day walltime but received a 24-hour walltime instead, or something along those lines.
