### ISSUE TITLE
Template version control

### ISSUE THREAD

**Issue by awchrist** [tgen/jetstream#91]
Today we can provide a pipeline with a version "phoenix@development" or "phoenix@v1.0.1". We will want to increment the version in the future to "phoenix@v1.2.0". I believe this causes jetstream to through an error. We will add tasks in the future that will be part of the newer version but want to allow people to rerun there there projects with the newer version of "phoenix" without a jetstream error. Can we reduce the validation in jetstream to allow multiple version of of the same "phoenix" workflow to be run?

**Comment by ryanrichholt** [comment]
Do you have an example of the error message I can look at?

**Comment by awchrist** [comment]
I was wrong. Must have fat fingered something.
